"""Hooks system: event types and service for agent lifecycle events."""

from tau.hooks.engine import (
    AgentEndEvent,
    AgentEndReason,
    AgentErrorEvent,
    AgentStartEvent,
    BeforeAgentStartEvent,
    BeforeAgentStartEventResult,
    BeforeCompactionEvent,
    BeforeCompactionResult,
    CompactionEndEvent,
    CompactionStartEvent,
    ContextEvent,
    ContextEventResult,
    MessageEndEvent,
    MessageEndEventResult,
    MessageStartEvent,
    MessageUpdateEvent,
    SavePointEvent,
    SettledEvent,
    ToolCallEvent,
    ToolCallEventResult,
    ToolExecutionEndEvent,
    ToolExecutionFailureEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    ToolResultEvent,
    ToolResultEventResult,
    TurnEndEvent,
    TurnStartEvent,
)
from tau.hooks.inference import (
    AfterProviderResponseEvent,
    BeforeProviderRequestEvent,
)
from tau.hooks.runtime import (
    InputEvent,
    InputEventResult,
    ProjectTrustEvent,
    ProjectTrustResult,
    ResourcesDiscoverEvent,
    ResourcesDiscoverResult,
    RuntimeReadyEvent,
    RuntimeStartEvent,
    RuntimeStopEvent,
    TerminalExecutionEvent,
    TerminalOutputEvent,
    UserTerminalEvent,
    UserTerminalResult,
)
from tau.hooks.service import Hooks
from tau.hooks.session import (
    SessionBeforeForkEvent,
    SessionBeforeForkResult,
    SessionBeforeSwitchEvent,
    SessionBeforeSwitchReason,
    SessionBeforeSwitchResult,
    SessionBeforeTreeEvent,
    SessionBeforeTreeResult,
    SessionShutdownEvent,
    SessionShutdownReason,
    SessionStartEvent,
    SessionStartReason,
    SessionTreeEvent,
    TreePreparation,
)
from tau.hooks.tui import (
    ModelSelectEvent,
    QueueUpdateEvent,
    ThinkingLevelSelectEvent,
    TuiExitEvent,
    TuiReadyEvent,
    TuiStartEvent,
)
from tau.hooks.types import HookEvent

__all__ = [
    "Hooks",
    "HookEvent",
    # Session
    "SessionStartReason",
    "SessionShutdownReason",
    "SessionBeforeSwitchReason",
    "SessionStartEvent",
    "SessionBeforeSwitchEvent",
    "SessionBeforeForkEvent",
    "SessionShutdownEvent",
    "TreePreparation",
    "SessionBeforeTreeEvent",
    "SessionTreeEvent",
    "SessionBeforeSwitchResult",
    "SessionBeforeForkResult",
    "SessionBeforeTreeResult",
    # Engine
    "AgentEndReason",
    "ContextEvent",
    "BeforeAgentStartEvent",
    "AgentStartEvent",
    "AgentEndEvent",
    "AgentErrorEvent",
    "TurnStartEvent",
    "TurnEndEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "MessageEndEvent",
    "ToolExecutionFailureEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "ToolExecutionEndEvent",
    "ToolCallEvent",
    "ToolResultEvent",
    "SavePointEvent",
    "SettledEvent",
    "BeforeCompactionResult",
    "BeforeCompactionEvent",
    "CompactionStartEvent",
    "CompactionEndEvent",
    "ContextEventResult",
    "ToolCallEventResult",
    "ToolResultEventResult",
    "MessageEndEventResult",
    "BeforeAgentStartEventResult",
    # Inference
    "BeforeProviderRequestEvent",
    "AfterProviderResponseEvent",
    # TUI
    "TuiReadyEvent",
    "TuiStartEvent",
    "TuiExitEvent",
    "ModelSelectEvent",
    "ThinkingLevelSelectEvent",
    "QueueUpdateEvent",
    # Runtime
    "InputEvent",
    "UserTerminalEvent",
    "TerminalExecutionEvent",
    "TerminalOutputEvent",
    "ResourcesDiscoverEvent",
    "ProjectTrustEvent",
    "RuntimeStartEvent",
    "RuntimeReadyEvent",
    "RuntimeStopEvent",
    "InputEventResult",
    "UserTerminalResult",
    "ResourcesDiscoverResult",
    "ProjectTrustResult",
]
